# Generated by Django 5.1.4 on 2025-01-27 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ('name',), 'verbose_name_plural': 'ProductCategories'},
        ),
    ]
